name: HTTP Request Action
on: [push]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: getrequest
        id: query
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/todos?id=1'
